services:
  # Go, Java, etc.

  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UT-8080}:${PORT_WEB_UI-8080}"
    environment:
      SERVICES: s3
      DATA_DIR: /tmp/localstack/data
      DEBUG: 1

  db:
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: postgresql
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      TZ: "Asia/Tokyo"
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    user:
      root
