services:
  # Go, Java, etc.

  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UT-8080}:${PORT_WEB_UI-8080}"
    environment:
      SERVICES: s3
      DATA_DIR: /tmp/localstack/data
      DEBUG: 1
  # LocalStack(AWS) Command Memo : 
  # $ aws s3 mb s3://local-backet --endpoint-url=http://localhost:4566
  # $ aws s3 cp TEST.txt s3://local-backet/test/ --endpoint-url=http://localhost:4566
  # $ aws s3 ls s3://local-backet/test/ --endpoint-url=http://localhost:4566

  db:
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: postgresql
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      TZ: "Asia/Tokyo"
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    user:
      root
  # DB Command Memo : 
  # $ docker-compose exec db psql -U postgres
  # $ sudo chmod 755 ./postgres-data
